# Сетевые порты
listeners.tcp.default = 5672
management.tcp.port = 15672

# Безопасность
loopback_users.guest = false

# Защита от переполнения диска
disk_free_limit.absolute = 500MB

# Heartbeat (согласовано с приложением)
heartbeat = 600
