"""2.0.

Revision ID: 0eaffc6617c8
Revises: 52b03b61f10d
Create Date: 2026-03-23 13:56:28.669310

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '0eaffc6617c8'
down_revision: Union[str, None] = '52b03b61f10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
