"""auto.

Revision ID: 52b03b61f10d
Revises:
Create Date: 2026-03-21 22:59:52.331813

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '52b03b61f10d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'action',
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('photo_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_action')),
    )
    op.create_table(
        'cafe',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('photo_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_cafe')),
    )
    op.create_table(
        'dish',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('photo_id', sa.UUID(), nullable=False),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_dish')),
    )
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_dish_name'),
            ['name'],
            unique=False,
        )

    op.create_table(
        'user',
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=255), nullable=True),
        sa.Column(
            'role',
            sa.Enum('ADMINISTRATOR', 'MANAGER', 'USER', name='userrole'),
            nullable=False,
        ),
        sa.Column('tg_id', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
        sa.UniqueConstraint('email', name=op.f('uq_user_email')),
        sa.UniqueConstraint('tg_id', name=op.f('uq_user_tg_id')),
        sa.UniqueConstraint('username', name=op.f('uq_user_username')),
    )
    op.create_table(
        'booking',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.Column('guest_number', sa.Integer(), nullable=False),
        sa.Column('note', sa.String(length=255), nullable=True),
        sa.Column('status', sa.Integer(), nullable=False),
        sa.Column('booking_date', sa.Date(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['cafe_id'],
            ['cafe.id'],
            name=op.f('fk_booking_cafe_id_cafe'),
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
            name=op.f('fk_booking_user_id_user'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_booking')),
    )
    op.create_table(
        'cafe_action',
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.Column('action_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['action_id'],
            ['action.id'],
            name=op.f('fk_cafe_action_action_id_action'),
        ),
        sa.ForeignKeyConstraint(
            ['cafe_id'],
            ['cafe.id'],
            name=op.f('fk_cafe_action_cafe_id_cafe'),
        ),
        sa.PrimaryKeyConstraint(
            'cafe_id',
            'action_id',
            name=op.f('pk_cafe_action'),
        ),
    )
    op.create_table(
        'cafe_dish',
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.Column('dish_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['cafe_id'],
            ['cafe.id'],
            name=op.f('fk_cafe_dish_cafe_id_cafe'),
        ),
        sa.ForeignKeyConstraint(
            ['dish_id'],
            ['dish.id'],
            name=op.f('fk_cafe_dish_dish_id_dish'),
        ),
        sa.PrimaryKeyConstraint(
            'cafe_id',
            'dish_id',
            name=op.f('pk_cafe_dish'),
        ),
    )
    op.create_table(
        'cafe_manager',
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['cafe_id'],
            ['cafe.id'],
            name=op.f('fk_cafe_manager_cafe_id_cafe'),
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
            name=op.f('fk_cafe_manager_user_id_user'),
        ),
        sa.PrimaryKeyConstraint(
            'cafe_id',
            'user_id',
            name=op.f('pk_cafe_manager'),
        ),
    )
    op.create_table(
        'refresh_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('jti', sa.UUID(), nullable=False),
        sa.Column('token_hash', sa.String(length=64), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'revoked',
            sa.Boolean(),
            server_default='false',
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
            name=op.f('fk_refresh_tokens_user_id_user'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_refresh_tokens_jti'),
            ['jti'],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f('ix_refresh_tokens_token_hash'),
            ['token_hash'],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f('ix_refresh_tokens_user_id'),
            ['user_id'],
            unique=False,
        )

    op.create_table(
        'table',
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('seat_number', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['cafe_id'],
            ['cafe.id'],
            name=op.f('fk_table_cafe_id_cafe'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_table')),
    )
    op.create_table(
        'time_slot',
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=False),
        sa.Column('end_time', sa.Time(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['cafe_id'],
            ['cafe.id'],
            name=op.f('fk_time_slot_cafe_id_cafe'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_time_slot')),
    )
    op.create_table(
        'booking_slot',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('slot_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['booking_id'],
            ['booking.id'],
            name=op.f('fk_booking_slot_booking_id_booking'),
        ),
        sa.ForeignKeyConstraint(
            ['slot_id'],
            ['time_slot.id'],
            name=op.f('fk_booking_slot_slot_id_time_slot'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_slot')),
    )
    op.create_table(
        'booking_table',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('table_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['booking_id'],
            ['booking.id'],
            name=op.f('fk_booking_table_booking_id_booking'),
        ),
        sa.ForeignKeyConstraint(
            ['table_id'],
            ['table.id'],
            name=op.f('fk_booking_table_table_id_table'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_table')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_table')
    op.drop_table('booking_slot')
    op.drop_table('time_slot')
    op.drop_table('table')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    op.drop_table('cafe_manager')
    op.drop_table('cafe_dish')
    op.drop_table('cafe_action')
    op.drop_table('booking')
    op.drop_table('user')
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_name'))

    op.drop_table('dish')
    op.drop_table('cafe')
    op.drop_table('action')
    # ### end Alembic commands ###
